 - name: install python
   ansible.builtin.dnf:
    name: "{{item}}"
    state: present
   loop:
   - python3
   - gcc
   - python3-devel
    # dnf install python3 gcc python3-devel -y
  
 - name: dependencies download
   ansible.builtin.command: pip3 install -r requirements.txt
   args:
    chdir: /app